services:
  # Servicio Web único para backend + frontend
  - type: web
    name: dopmax-buena
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: dopmaxx
          property: connectionString

databases:
  - name: dopmaxx
    databaseName: dopmaxx
    user: dopmaxx_user
    plan: free
    region: frankfurt
