services:
  # Servicio Web único para backend + frontend
  - type: web
    name: dopmax-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://dopmaxx_user:AxAOCstUlJECm8KZePvgUjRcmmbA6Alk@dpg-d6q0ekpj16oc73boo1m0-a/dopmaxx
